### ISSUE TITLE
Return `merModMultiMember` type

### ISSUE THREAD

**Issue by palday** [jvparidon/lmerMultiMember#1]
well, that type combined with `lmerMod` :)

**Comment by palday** [comment]
@jvparidon I agree

We need to provide good ways to query/summarize them. The `image` code in the vignette doesn't introduce any additional dependencies, so it might be good to wrap that in a function for merModMultiMember.

**Comment by jvparidon** [comment]
Any ideas for what we should call that method? (e.g. `plot_memberships.merModMultiMember` or something?)

**Comment by palday** [comment]
If we're using a clear / problem-unique name like that, then we don't even need to bother with S3/S4 and can just call it `plot_memberships`

**Comment by jvparidon** [comment]
Added plotting features in #25. Do we need anything else before we cross this off our list?

**Comment by jvparidon** [comment]
Closing this because #25 and #26 basically cover it. #26 is a little experimental so we may need to fix some bugs, but those should be separate issues.
