### ISSUE TITLE
Test whether different methods for computing CIs work with lmerMultiMember

### ISSUE THREAD

**Issue by jvparidon** [jvparidon/lmerMultiMember#27]
Supporting lmerTest is very messy; definitely suboptimal. If we can get degrees of freedom using the hat matrix instead and just drop lmerTest support, that seems preferable.

Let's use this issue to collate theoretical and practical considerations as we work on implementation.

**Comment by jvparidon** [comment]
See https://stat.ethz.ch/pipermail/r-help/2006-September/112723.html and preceding discussion.

**Comment by palday** [comment]
It might be worthwhile to just not offer ddf and say that all the complexities of the ddf (whether you're actually following an F distribution at all; what residual df even mean in this content) are even worse for multimembership models than for single membership/classical models

**Comment by jvparidon** [comment]
So do we only support profile likelihood confidence intervals then? (Those seem to work out of the box, but I'm not quite sure of the correctness of the assumptions for those, either.)

**Comment by palday** [comment]
Profiling should be correct. I think bootstrap will also be correct (assuming it runs) because it re-uses the model matrices for simulation and just takes new draws for the estimated random effects and residual errors.

**Comment by jvparidon** [comment]
Just going to change the title of this issue to reflect that what's needed now is:
- [ ] Test whether profile likelihood CIs work.
- [ ] Test whether bootstrapping works.
- [ ] Add unit tests for profile likelihood CIs.
- [ ] Add unit tests for bootstrapping.
