### ISSUE TITLE
Modeling Longitudinal Data

### ISSUE THREAD

**Issue by wetherij** [jvparidon/lmerMultiMember#57]
I’m designing a dose titration trial to explore the relationship between dose and an adverse event of special interest, and would greatly appreciate your guidance in analyzing the planned results.  The goal is to estimate the probability of this adverse event for each dose.  
Salient features of the design include:
•	Three cohorts will be studied (only two shown in the figure below) with 12 patients per cohort on drug and 4 patients per cohort on placebo.
•	Every patient within a cohort will start on the same dose (e.g., Dose 1 in Cohort 1).
•	Each cohort will undergo three dosing periods (e.g., Dose 1, Dose 2, Dose 3 in Cohort 1)
•	The starting dose in Cohort i+1 can be the last dose in Cohort i (e.g., Dose 3 in Cohort 2).
•	Doses are increasing (Dose i+1 > Dose i).
•	Each patient will be dosed once per day within a dosing period for three weeks.
•	After three weeks, the dose for each patient within a cohort can be up titrated, down titrated, or remain unchanged based on pre-specified titration rules.
•	Based on the titration rules, a patient within each cohort can remain at the starting dose for all three dosing periods (e.g., Dose 3 in Cohort 2), or a patient can remain at the second dose for two dosing periods.
•	Dose is assumed to be continuous effect and patient a random effect.

How can the longitudinal nature of these data be “communicated” to the lme4 via lmerMultiMember?  Specifically, what is the structure of the pre-generated indicator matrix for the nested factor?  Will a solution work for the rstanarm version of lme4 as the goal is to analyze the data in a Bayesian framework?  I’ve attached a toy dataset which I hope will give you a better idea of the structure of the clinical design.
Thank you in advance for your help with this.

 
![image](https://github.com/jvparidon/lmerMultiMember/assets/105369876/e8e68798-7728-49b5-aaf3-c74de3132d46)

[toy.csv](https://github.com/jvparidon/lmerMultiMember/files/11652994/toy.csv)

**Comment by jvparidon** [comment]
Hey, I'm sorry I didn't respond to this at the time that it was posted.

My tardiness in responding aside, this question is a little outside of the scope of what I'd consider an "issue" with the `lmerMultiMember` package. I'm always happy to help with basic questions about how to use the package and with any bugs or feature requests that may come up. However, I think what you are looking for is a statistical consultant to help analyze your study, which is not work I do for free (or do at all, at present).

I'm going to close this issue, but if you're still interested in having your questions answered, I recommend seeking out a statistical consultant at the institution or company you work at, or perhaps posting your question on CrossValidated/StackExchange.
