### ISSUE TITLE
Fail to install lmerMultiMember on M2 Mac

### ISSUE THREAD

**Issue by kylecnewton** [jvparidon/lmerMultiMember#62]
Hi, 

I cant seem to install the package on my M2 Macbook Pro running MacOS Sonoma 14.2.1. Error is pasted below

edit: running R Studio - Version 2023.09.0+463 (2023.09.0+463)

thanks for any help 

- Kyle

> if(!require(devtools)){
+     install.packages("devtools")
+     library("devtools")
+ }
> 
> install_github("jvparidon/lmerMultiMember")
Downloading GitHub repo jvparidon/lmerMultiMember@HEAD
Error: Failed to install 'lmerMultiMember' from GitHub:
  lazy-load database '/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/pkgbuild/R/pkgbuild.rdb' is corrupt
In addition: Warning messages:
1: In safe_build_package(pkgdir, build_opts, build_manual, build_vignettes,  :
  restarting interrupted promise evaluation
2: In safe_build_package(pkgdir, build_opts, build_manual, build_vignettes,  :
  internal error -5 in R_decompress1
>

**Comment by kylecnewton** [comment]
forgot to add. 

R studio - Version 2023.09.0+463 (2023.09.0+463)

**Comment by palday** [comment]
This isn't an lmerMultiMember issue, but you could potentially resolve it by deleting the corrupt lazy-load database. You may have to reinstall all your packages afterwards though.

**Comment by jvparidon** [comment]
Since this isn't an lmerMultiMember issue I'm going to close this.
I hope Phillip's advice helped solve this issue for you @kylecnewton!
